apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  namespace: dev
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8080

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: playground-deployment
  namespace: dev
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`192.168.56.162`) # && Path(`test`)
      priority: 10
      services:
        - name: playground-ingress
          port: 8080
