apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
spec:
  selector:
    matchLabels:
      app: playground-deployment
  template:
    metadata:
      labels:
        app: playground-deployment
    spec:
      containers:
        - name: playground-deployment
          image: wil42/playground:v1
---
apiVersion: v1
kind: Service
metadata:
  name: playground-deployment
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: playground-deployment
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: playground-deployment
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Path(`/wakkapp`)
    services:
    - kind: Service
      name: playground-deployment
      port: 80
