apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 3
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: paulbouwer/hello-kubernetes:1
          env:
            - name: MESSAGE
              value: Hello from app2
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app2
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`192.168.56.162`)
    services:
    - kind: Service
      name: app2
      port: 80
